'use client';

import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { fetchMyDocument, downloadMyDocumentPdf } from '@/lib/api/documents';
import Icon from '@/components/ui/Icon';
import Container from '@/components/ui/Container';

export default function MyDocumentPage() {
  const { id } = useParams<{ id: string }>();
  const q = useQuery({ queryKey: ['my-document', id], queryFn: () => fetchMyDocument(id), enabled: !!id });
  const doc = q.data;
  const paid = doc && doc.status !== 'DRAFT' && doc.contentHtml;
  const [dlErr, setDlErr] = useState('');

  return (
    <Container className="py-8">
      <div className="mb-5 flex items-center justify-between print:hidden">
        <Link href="/dashboard/documents" className="rounded-xl border border-gray-200 px-4 py-2 text-sm font-semibold text-slate-600 hover:border-gold hover:text-navy">
          <Icon name="chevron-left" aria-hidden="true" className="mr-1 text-xs" /> My documents
        </Link>
        {paid && (
          <div className="flex gap-2">
            <button
              onClick={async () => {
                setDlErr('');
                try {
                  await downloadMyDocumentPdf(id, `${doc!.template.title}.pdf`);
                } catch (e) {
                  setDlErr(e instanceof Error ? e.message : 'Download failed');
                }
              }}
              className="rounded-xl border border-gray-200 px-5 py-2 text-sm font-bold text-navy hover:border-gold"
            >
              <Icon name="download" aria-hidden="true" className="mr-1" /> Download PDF
            </button>
            <button onClick={() => window.print()} className="rounded-xl bg-navy px-5 py-2 text-sm font-bold text-white hover:bg-slate-800">
              <Icon name="print" aria-hidden="true" className="mr-1" /> Print
            </button>
          </div>
        )}
      </div>

      {dlErr && (
        <p role="alert" className="mb-4 rounded-lg bg-rose-50 px-3 py-2 text-sm text-rose-700 print:hidden">{dlErr}</p>
      )}
      {q.isLoading && <p role="status" className="text-sm text-slate-400">Loading…</p>}
      {q.isError && (
        <p role="alert" className="rounded-lg bg-rose-50 px-3 py-2 text-sm text-rose-700 print:hidden">{(q.error as Error).message}</p>
      )}

      {doc && !paid && (
        <div className="rounded-2xl border border-amber-200 bg-amber-50 p-6 text-sm text-amber-800">
          <p className="font-bold">Payment pending</p>
          <p className="mt-1">
            This draft hasn&apos;t been paid for yet. Restart the purchase from{' '}
            <Link href={`/legal-documents/${doc.template.slug}`} className="font-semibold underline">the template page</Link>.
          </p>
        </div>
      )}

      {paid && doc && (
        <article className="rounded-2xl border border-gray-200 bg-white p-8 print:border-0 print:p-0">
          <h1 className="mb-1 text-xl font-extrabold text-navy">{doc.template.title}</h1>
          <p className="mb-6 text-[11px] text-slate-400 print:hidden">
            Purchased {new Date(doc.createdAt).toLocaleDateString()} · keep a signed copy for your records
          </p>
          {doc.template.requiresStamp && (
            <p className="mb-5 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs text-amber-700 print:hidden">
              <Icon name="file-shield" aria-hidden="true" className="mr-1" />
              This document needs stamp paper{doc.template.stampBasis ? ` (${doc.template.stampBasis.toLowerCase()})` : ''} —
              print it on / attach e-stamp paper of the correct value for your state before signing.
            </p>
          )}
          <pre className="whitespace-pre-wrap break-words font-serif text-[15px] leading-relaxed text-slate-800">
            {doc.contentHtml}
          </pre>
          <p className="mt-8 border-t border-gray-100 pt-4 text-[10px] text-slate-400">
            Generated by LawMitran from your answers. Self-help template — not legal advice.
          </p>
        </article>
      )}
    </Container>
  );
}
